version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: security
      POSTGRES_PASSWORD: security
      POSTGRES_DB: security
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: [minio:/data]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8080:8080"]

  api-agent:
    build: ./services/api-agent
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OIDC_ISSUER: ${OIDC_ISSUER}
    ports: ["8082:8082"]
    depends_on: [postgres, keycloak]

  api-admin:
    build: ./services/api-admin
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OIDC_ISSUER: ${OIDC_ISSUER}
      JWT_JWKS_URI: ${JWT_JWKS_URI}
      ADMIN_API_PORT: ${ADMIN_API_PORT}
    ports: ["8081:8081"]
    depends_on: [postgres, keycloak]

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_ADMIN_API_BASE: http://localhost:8081
      NEXT_PUBLIC_OIDC_ISSUER: ${OIDC_ISSUER}
      NEXT_PUBLIC_OIDC_CLIENT_ID: admin-ui
    ports: ["3000:3000"]
    depends_on: [api-admin]

volumes:
  pgdata:
  minio:
